rootProject.name = "design-patterns"
include("correcion")
include("factory-method")

include("mediator")
include("correcion")
include("singleton")
include("adapter")
include("bridge")
include("composite")
include("decorator")
include("proxy")
include("command")
include("memento")
include("observer")
include("visitor")